### PR TITLE
Fix(api)/ssh key generation

### LINKED ISSUE #760: Repo cloner is not being able to pull Github repos
When a Github repository is added as an external project Repo Cloner is being unable to clone it:
```
2022-03-16T11:56:43.076846486+01:00 2022-03-16T10:56:43.076717215Z INFO Found 1 new repositories to clone                                                                                                  
2022-03-16T11:56:43.079923796+01:00 2022-03-16T10:56:43.079829571Z INFO github.com is a known host                                                                                                         
2022-03-16T11:56:43.079957550+01:00 2022-03-16T10:56:43.079851039Z DEBUG Repository ny-house-price-estim with URL ssh://git@github.com/konstellation-io/ny-house-price-estimator.git found. Clone starting 
2022-03-16T11:56:44.202325914+01:00 2022-03-16T10:56:44.202195556Z ERROR Error cloning repository: unknown error: ERROR: You're using an RSA key with SHA-1, which is no longer allowed. Please use a newer client or a different key type. 
 ```
 
This is due the generated RSA keys are not being validated by Github sice they changed their acceptance key policy on March 15th:  https://github.blog/2021-09-01-improving-git-protocol-security-github/#when-are-these-changes-effective

### PR DESCRIPTION
**Pull request by rrbarrero**
Because the rsa sha1 have been deprecated by github we change to new type of key generation ED25519

Closes #760

### CODE REVIEW

File: app/api/pkg/sshhelper/generator.go [hunk 1]
```diff
@@ -26,75 +27,35 @@ func NewGenerator(logger logging.Logger) SSHKeyGenerator {
...
 		Private:      string(privateKeyBytes),
 		CreationDate: time.Now().UTC(),
 	}, nil
 }
 
-// generatePrivateKey creates a RSA Private Key of specified byte size.
-func (g *generator) generatePrivateKey(bitSize int) (*rsa.PrivateKey, error) {
-	// Private Key generation
-	privateKey, err := rsa.GenerateKey(rand.Reader, bitSize)
+func (g *generator) generateKeyPair() (public, private []byte, err error) {
```
Comment (JYisus) [inline app/api/pkg/sshhelper/generator.go:42]: @rrbarrero Just a little comment (don't change anything): I don't know if putting the name of the variables in the return types is a good practice. It's more readable because the order of the returned values is important, but we have to be careful with the behavior of the returns in this cases.

**Review by JYisus — APPROVED** [review]
Great job!

File: app/api/pkg/sshhelper/generator.go (hunk 1 above)
Comment (rrbarrero) [reply app/api/pkg/sshhelper/generator.go:42]: Thank you mates, it remains to talk about this.

File: app/api/pkg/sshhelper/generator.go [hunk 2]
```diff
@@ -26,75 +27,35 @@ func NewGenerator(logger logging.Logger) SSHKeyGenerator {
...
-	// Get ASN.1 DER format
-	privDER := x509.MarshalPKCS1PrivateKey(privateKey)
-
-	// pem.Block
-	privBlock := pem.Block{
-		Type:    "RSA PRIVATE KEY",
-		Headers: nil,
-		Bytes:   privDER,
+	pemKey := &pem.Block{
+		Type:  "OPENSSH PRIVATE KEY",
```
Comment (alexrodfe) [inline app/api/pkg/sshhelper/generator.go:54]: I'm curious about this string, is it a free field within the pem.Block structure, info for us, or is it a defined string?

**Review by alexrodfe — APPROVED** [review]
Cool! Just a couple of questions.
